#
# Configuration file for markdownlint-cli2. This file defines what rules to use when linting
# markdown files. For more details see:
#    https://github.com/DavidAnson/markdownlint
#

# Disables or enables rules
config:
  # Enables line-length rule to warn on lines longer than 100 characters
  MD013:
    line_length: 100
    # The spacing of the copybooks and the file examples makes it impractical to limit the length
    # of the code blocks
    code_blocks: false

# Fix any fixable errors
fix: true

# Define glob expressions to use (only valid at root)
# globs:
#   - "!*bout.md"

# Define glob expressions to ignore
ignores:
  - ".github/pull_request_template.md"

# Disable inline config comments
noInlineConfig: true
