# This workflow will lint markdown documents for consistency
name: Markdown Linter

on:
  push:
    branches: [ "main", "3/create-docs-folder" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.md'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v3

    - name: Markdown Linting Action
      uses: DavidAnson/markdownlint-cli2-action@v9
      with:
        globs: '**/*.md'
        config: '.markdownlint-cli2.yaml'

